// <auto-generated />
using System;
using Hrubos.HospitalSystem.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hrubos.HospitalSystem.Infrastructure.Migrations
{
    [DbContext(typeof(HospitalSystemDbContext))]
    [Migration("20251118091531_mysql_1.0.7_examinationResult")]
    partial class mysql_107_examinationResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.DoctorPatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("DoctorPatient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 2,
                            PatientId = 6
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 3,
                            PatientId = 7
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 4,
                            PatientId = 8
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 2,
                            PatientId = 8
                        },
                        new
                        {
                            Id = 5,
                            DoctorId = 5,
                            PatientId = 7
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Examination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ExaminationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ExaminationTypeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Examination");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2025, 11, 8, 10, 15, 29, 834, DateTimeKind.Local).AddTicks(5489),
                            DoctorId = 2,
                            ExaminationTypeId = 1,
                            PatientId = 6,
                            ProblemDescription = "Vysoký tlak"
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2025, 11, 13, 10, 15, 29, 836, DateTimeKind.Local).AddTicks(8203),
                            DoctorId = 3,
                            ExaminationTypeId = 3,
                            PatientId = 7,
                            ProblemDescription = "Krevní test"
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2025, 11, 16, 10, 15, 29, 836, DateTimeKind.Local).AddTicks(8228),
                            DoctorId = 4,
                            ExaminationTypeId = 2,
                            PatientId = 8,
                            ProblemDescription = "Bolest kloubů"
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2025, 11, 10, 10, 15, 29, 836, DateTimeKind.Local).AddTicks(8231),
                            DoctorId = 4,
                            ExaminationTypeId = 2,
                            PatientId = 7,
                            ProblemDescription = "Bolest zápěstí"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.ExaminationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentSrc")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExaminationId")
                        .HasColumnType("int");

                    b.Property<string>("Values")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationId")
                        .IsUnique();

                    b.ToTable("ExaminationResult");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "vše v pořádku",
                            ExaminationId = 1,
                            Values = "TK: 120/80, Puls: 72"
                        },
                        new
                        {
                            Id = 2,
                            Description = "lehká anémie",
                            ExaminationId = 2,
                            Values = "Hemoglobin: 110 g/l, Hct: 33%"
                        },
                        new
                        {
                            Id = 3,
                            AttachmentSrc = "/attachments/examinationResults/cloub_knee_xray.jpg",
                            Description = "artritida kolene",
                            ExaminationId = 3,
                            Values = "RTG: mírná artritida, rentgenový snímek v příloze"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.ExaminationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.HasKey("Id");

                    b.ToTable("ExaminationType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Obvodní vyšetření"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Specialistické vyšetření"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laboratorní test"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Specialization");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oftalmologie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chirurgie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pediatrie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kardiologie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pneumologie"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SystemSetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "MaxVaccinationPerDay",
                            Value = "20"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Vaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("VaccineTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("VaccineTypeId");

                    b.ToTable("Vaccination");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2024, 11, 18, 10, 15, 29, 837, DateTimeKind.Local).AddTicks(6200),
                            PatientId = 6,
                            VaccineTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2025, 3, 18, 10, 15, 29, 837, DateTimeKind.Local).AddTicks(6915),
                            PatientId = 7,
                            VaccineTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2025, 5, 18, 10, 15, 29, 837, DateTimeKind.Local).AddTicks(6924),
                            PatientId = 8,
                            VaccineTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2025, 8, 18, 10, 15, 29, 837, DateTimeKind.Local).AddTicks(6927),
                            PatientId = 6,
                            VaccineTypeId = 2
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.VaccineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.HasKey("Id");

                    b.ToTable("VaccineType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chřipka"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hepatitida B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tetanus"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Infrastructure.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "9cf14c2c-19e7-40d6-b744-8917505c3106",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "be0efcde-9d0a-461d-8eb6-444b043d6660",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "29dafca7-cd20-4cd9-a3dd-4779d7bac3ee",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Infrastructure.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BirthNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MaxExaminationPerDay")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SpecializationId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "de87a082-5461-40fe-9f7f-7119ffec0f60",
                            Email = "admin@admin.cz",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Martin",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@ADMIN.CZ",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEC4prnSMIdRUykdd65G87+g3lLCc9cqJ/re6T1TsQFv5xlMrmVIe4k7yMQiEYWpH3A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f38409844898492483187f69130e973f",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "59ea360b-0776-4e99-aeb9-10668f24f758",
                            Email = "jan.novak@nemocnice.cz",
                            EmailConfirmed = true,
                            FirstName = "Jan",
                            LastName = "Novák",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 10,
                            NormalizedEmail = "JAN.NOVAK@NEMOCNICE.CZ",
                            NormalizedUserName = "DOCTOR1",
                            PasswordHash = "AQAAAAEAACcQAAAAECxrKr4YAVakrkIYFy7MgUA11ryq0Sgun00+cj9FnR6EHzH8EL9WRc3J60f5x2nv0g==",
                            PhoneNumber = "111222333",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3d98cd58736245a19cafb57b12e671a5",
                            SpecializationId = 1,
                            TwoFactorEnabled = false,
                            UserName = "doctor1"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "52022b32-75f1-41a5-9b63-2304ed5bf072",
                            Email = "petr.svoboda@nemocnice.cz",
                            EmailConfirmed = true,
                            FirstName = "Petr",
                            LastName = "Svoboda",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 5,
                            NormalizedEmail = "PETR.SVOBODA@NEMOCNICE.CZ",
                            NormalizedUserName = "DOCTOR2",
                            PasswordHash = "AQAAAAEAACcQAAAAEK4DkND+5IwQiNI01DelkSwKPGQnzZAxCmobmvF3J0w5Xr6YO4bUtzjJwe2qRzUv7g==",
                            PhoneNumber = "222333444",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f423f1802efe4b9dbf0bd391c0edb8e2",
                            SpecializationId = 2,
                            TwoFactorEnabled = false,
                            UserName = "doctor2"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f55301f4-7dc5-40bc-8b70-0c52ad249369",
                            Email = "lucie.dvorakova@nemocnice.cz",
                            EmailConfirmed = true,
                            FirstName = "Lucie",
                            LastName = "Dvořáková",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 2,
                            NormalizedEmail = "LUCIE.DVORAKOVA@NEMOCNICE.CZ",
                            NormalizedUserName = "DOCTOR3",
                            PasswordHash = "AQAAAAEAACcQAAAAEMK02V+4Wdm0lgraNwSBHPhhYUFmVpoCrp103XwzNXTFK6/s8xx0AAdpsd2G2KquQQ==",
                            PhoneNumber = "333444555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d9da53a1deb746e2ba05339c507252e1",
                            SpecializationId = 3,
                            TwoFactorEnabled = false,
                            UserName = "doctor3"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2faea44-bf57-408b-a3a8-c37af5b967e6",
                            Email = "arnost.patek@nemocnice.cz",
                            EmailConfirmed = true,
                            FirstName = "Arnošt",
                            LastName = "Pátek",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 0,
                            NormalizedEmail = "ARNOST.PATEK@NEMOCNICE.CZ",
                            NormalizedUserName = "DOCTOR4",
                            PasswordHash = "AQAAAAEAACcQAAAAEGrcdYyAHwCXTbk9VS3VItkcEq4bhgiPBFetA8rLbp/6Asw87PI2TqWE5csu8u6TDA==",
                            PhoneNumber = "444555666",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64a659de93ab49918f6fc67dec0b2b3e",
                            SpecializationId = 2,
                            TwoFactorEnabled = false,
                            UserName = "doctor4"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            BirthNumber = "900101/1234",
                            ConcurrencyStamp = "8cb9e147-131a-442a-a62d-731c5277658b",
                            Email = "tomas.horak@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Tomáš",
                            LastName = "Horák",
                            LockoutEnabled = true,
                            NormalizedEmail = "TOMAS.HORAK@EMAIL.CZ",
                            NormalizedUserName = "PACIENT1",
                            PasswordHash = "AQAAAAEAACcQAAAAEBacwHfAQ8oysuC+yEOFP2TakEie2+73wHf89V+TJX+Ioy5NfCTZkS0U/P5kN7yjmg==",
                            PhoneNumber = "601111111",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2d92ee082d9245ad86758e4405bdca8d",
                            TwoFactorEnabled = false,
                            UserName = "patient1"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            BirthNumber = "950202/2345",
                            ConcurrencyStamp = "976015b3-be92-4d8e-9965-aef4154491d9",
                            Email = "anna.mala@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Anna",
                            LastName = "Malá",
                            LockoutEnabled = true,
                            NormalizedEmail = "ANNA.MALA@EMAIL.CZ",
                            NormalizedUserName = "PACIENT2",
                            PasswordHash = "AQAAAAEAACcQAAAAEK31Pd3GzmAcXrVtoSezhRdeqGp0l5c6Zl0IjUvn6vAeslrjG7bgOuN4jHqQBRDbZA==",
                            PhoneNumber = "602222222",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "933bf2efeeb942468dcf20b0e6f4292e",
                            TwoFactorEnabled = false,
                            UserName = "patient2"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            BirthNumber = "880303/3456",
                            ConcurrencyStamp = "21d97ced-2483-44b4-97b7-0fb309d73910",
                            Email = "karel.novotny@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Karel",
                            LastName = "Novotný",
                            LockoutEnabled = true,
                            NormalizedEmail = "KAREL.NOVOTNY@EMAIL.CZ",
                            NormalizedUserName = "PACIENT3",
                            PasswordHash = "AQAAAAEAACcQAAAAEGDwHucn5uWF1684moFrwbqoaym+z0IHUiN+/EDQnXgz6HiEbGnaqFT136phybDc4g==",
                            PhoneNumber = "603333333",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f344aa64ec60426f894d2c247e2c4033",
                            TwoFactorEnabled = false,
                            UserName = "patient3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.DoctorPatient", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", "Doctor")
                        .WithMany("DoctorPatients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", "Patient")
                        .WithMany("PatientDoctors")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Examination", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", "Doctor")
                        .WithMany("DoctorExaminations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hrubos.HospitalSystem.Domain.Entities.ExaminationType", "ExaminationType")
                        .WithMany("Examinations")
                        .HasForeignKey("ExaminationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", "Patient")
                        .WithMany("PatientExaminations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("ExaminationType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.ExaminationResult", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Domain.Entities.Examination", "Examination")
                        .WithOne("Result")
                        .HasForeignKey("Hrubos.HospitalSystem.Domain.Entities.ExaminationResult", "ExaminationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examination");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Vaccination", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", "Patient")
                        .WithMany("Vaccinations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hrubos.HospitalSystem.Domain.Entities.VaccineType", "VaccineType")
                        .WithMany("Vaccinations")
                        .HasForeignKey("VaccineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("VaccineType");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Infrastructure.Identity.User", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Domain.Entities.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Examination", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.ExaminationType", b =>
                {
                    b.Navigation("Examinations");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.VaccineType", b =>
                {
                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Infrastructure.Identity.User", b =>
                {
                    b.Navigation("DoctorExaminations");

                    b.Navigation("DoctorPatients");

                    b.Navigation("PatientDoctors");

                    b.Navigation("PatientExaminations");

                    b.Navigation("Vaccinations");
                });
#pragma warning restore 612, 618
        }
    }
}
