// <auto-generated />
using System;
using Hrubos.HospitalSystem.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hrubos.HospitalSystem.Infrastructure.Migrations
{
    [DbContext(typeof(HospitalSystemDbContext))]
    partial class HospitalSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.DoctorPatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("DoctorPatient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 2,
                            PatientId = 6
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 3,
                            PatientId = 7
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 4,
                            PatientId = 8
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 2,
                            PatientId = 8
                        },
                        new
                        {
                            Id = 5,
                            DoctorId = 5,
                            PatientId = 7
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Examination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("ExaminationTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ExaminationTypeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Examination");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2025, 11, 29, 10, 55, 40, 9, DateTimeKind.Local).AddTicks(8342),
                            DoctorId = 2,
                            ExaminationTypeId = 1,
                            PatientId = 6,
                            ProblemDescription = "Vysoký tlak"
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2025, 12, 4, 10, 55, 40, 13, DateTimeKind.Local).AddTicks(2719),
                            DoctorId = 3,
                            ExaminationTypeId = 3,
                            PatientId = 7,
                            ProblemDescription = "Krevní test"
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2025, 12, 7, 10, 55, 40, 13, DateTimeKind.Local).AddTicks(2761),
                            DoctorId = 4,
                            ExaminationTypeId = 2,
                            PatientId = 8,
                            ProblemDescription = "Bolest kloubů"
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2025, 12, 1, 10, 55, 40, 13, DateTimeKind.Local).AddTicks(2767),
                            DoctorId = 4,
                            ExaminationTypeId = 2,
                            PatientId = 7,
                            ProblemDescription = "Bolest zápěstí"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.ExaminationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentSrc")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ExaminationId")
                        .HasColumnType("int");

                    b.Property<string>("Values")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationId")
                        .IsUnique();

                    b.ToTable("ExaminationResult");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Vše v pořádku",
                            ExaminationId = 1,
                            Values = "TK: 120/80, Puls: 72"
                        },
                        new
                        {
                            Id = 2,
                            AttachmentSrc = "\\attachments\\examinationResults\\erecept.png",
                            Description = "Lehká anémie",
                            ExaminationId = 2,
                            Values = "Hemoglobin: 110 g/l, Hct: 33%"
                        },
                        new
                        {
                            Id = 3,
                            AttachmentSrc = "\\attachments\\examinationResults\\rentgen.pdf",
                            Description = "Artritida kolene",
                            ExaminationId = 3,
                            Values = "RTG: mírná artritida, rentgenový snímek v příloze"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.ExaminationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ExaminationType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Obvodní vyšetření"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Specialistické vyšetření"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laboratorní test"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Specialization");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oftalmologie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chirurgie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pediatrie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kardiologie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pneumologie"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SystemSetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "MaxVaccinationsPerDay",
                            Value = "20"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Vaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("VaccineTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("VaccineTypeId");

                    b.ToTable("Vaccination");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2024, 12, 9, 10, 55, 40, 14, DateTimeKind.Local).AddTicks(6585),
                            PatientId = 6,
                            VaccineTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2025, 4, 9, 10, 55, 40, 14, DateTimeKind.Local).AddTicks(7857),
                            PatientId = 7,
                            VaccineTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2025, 6, 9, 10, 55, 40, 14, DateTimeKind.Local).AddTicks(7876),
                            PatientId = 8,
                            VaccineTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2025, 9, 9, 10, 55, 40, 14, DateTimeKind.Local).AddTicks(7880),
                            PatientId = 6,
                            VaccineTypeId = 2
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.VaccineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VaccineType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chřipka"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hepatitida B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tetanus"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Infrastructure.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "9cf14c2c-19e7-40d6-b744-8917505c3106",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "be0efcde-9d0a-461d-8eb6-444b043d6660",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "29dafca7-cd20-4cd9-a3dd-4779d7bac3ee",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Infrastructure.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BirthNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxExaminationPerDay")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fcd82561-a728-4982-bb84-203c22bd695d",
                            Email = "admin@admin.cz",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Martin",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 0,
                            NormalizedEmail = "ADMIN@ADMIN.CZ",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEC4prnSMIdRUykdd65G87+g3lLCc9cqJ/re6T1TsQFv5xlMrmVIe4k7yMQiEYWpH3A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "48d685f00a9b40f2a161b23ec17af18e",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9a27bf73-a31f-419e-815e-67f3f377ba41",
                            Email = "jan.novak@nemocnice.cz",
                            EmailConfirmed = true,
                            FirstName = "Jan",
                            LastName = "Novák",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 10,
                            NormalizedEmail = "JAN.NOVAK@NEMOCNICE.CZ",
                            NormalizedUserName = "DOCTOR1",
                            PasswordHash = "AQAAAAEAACcQAAAAECxrKr4YAVakrkIYFy7MgUA11ryq0Sgun00+cj9FnR6EHzH8EL9WRc3J60f5x2nv0g==",
                            PhoneNumber = "111222333",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f2a1471084c40afa4b538594ae6b318",
                            SpecializationId = 1,
                            TwoFactorEnabled = false,
                            UserName = "doctor1"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d29b6fc1-befe-4919-a0f0-4081f180ce4f",
                            Email = "petr.svoboda@nemocnice.cz",
                            EmailConfirmed = true,
                            FirstName = "Petr",
                            LastName = "Svoboda",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 5,
                            NormalizedEmail = "PETR.SVOBODA@NEMOCNICE.CZ",
                            NormalizedUserName = "DOCTOR2",
                            PasswordHash = "AQAAAAEAACcQAAAAEK4DkND+5IwQiNI01DelkSwKPGQnzZAxCmobmvF3J0w5Xr6YO4bUtzjJwe2qRzUv7g==",
                            PhoneNumber = "222333444",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0adef10c0dfb4fcf86471fd9a2364efc",
                            SpecializationId = 2,
                            TwoFactorEnabled = false,
                            UserName = "doctor2"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df9515fe-dd1d-4f21-b1a3-637978f4f6f8",
                            Email = "lucie.dvorakova@nemocnice.cz",
                            EmailConfirmed = true,
                            FirstName = "Lucie",
                            LastName = "Dvořáková",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 2,
                            NormalizedEmail = "LUCIE.DVORAKOVA@NEMOCNICE.CZ",
                            NormalizedUserName = "DOCTOR3",
                            PasswordHash = "AQAAAAEAACcQAAAAEMK02V+4Wdm0lgraNwSBHPhhYUFmVpoCrp103XwzNXTFK6/s8xx0AAdpsd2G2KquQQ==",
                            PhoneNumber = "333444555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f365b34905dc4391aee6173c400f1540",
                            SpecializationId = 3,
                            TwoFactorEnabled = false,
                            UserName = "doctor3"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10ed9b52-617b-427d-abaf-36e3495a3d5a",
                            Email = "arnost.patek@nemocnice.cz",
                            EmailConfirmed = true,
                            FirstName = "Arnošt",
                            LastName = "Pátek",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 0,
                            NormalizedEmail = "ARNOST.PATEK@NEMOCNICE.CZ",
                            NormalizedUserName = "DOCTOR4",
                            PasswordHash = "AQAAAAEAACcQAAAAEGrcdYyAHwCXTbk9VS3VItkcEq4bhgiPBFetA8rLbp/6Asw87PI2TqWE5csu8u6TDA==",
                            PhoneNumber = "444555666",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cace192898d844448e1ea36f47958e53",
                            SpecializationId = 2,
                            TwoFactorEnabled = false,
                            UserName = "doctor4"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            BirthNumber = "050510/2224",
                            ConcurrencyStamp = "1a55ba27-9cbd-40d9-a6d7-c88c53e196ab",
                            Email = "tomas.horak@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Tomáš",
                            LastName = "Horák",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 0,
                            NormalizedEmail = "TOMAS.HORAK@EMAIL.CZ",
                            NormalizedUserName = "PATIENT1",
                            PasswordHash = "AQAAAAEAACcQAAAAEBacwHfAQ8oysuC+yEOFP2TakEie2+73wHf89V+TJX+Ioy5NfCTZkS0U/P5kN7yjmg==",
                            PhoneNumber = "601111111",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ff20dde0bf124273b30aa848be5dd6f6",
                            TwoFactorEnabled = false,
                            UserName = "patient1"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            BirthNumber = "855801/0406",
                            ConcurrencyStamp = "15328eef-6f93-49f2-b670-5e9377b6e316",
                            Email = "anna.mala@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Anna",
                            LastName = "Malá",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 0,
                            NormalizedEmail = "ANNA.MALA@EMAIL.CZ",
                            NormalizedUserName = "PATIENT2",
                            PasswordHash = "AQAAAAEAACcQAAAAEK31Pd3GzmAcXrVtoSezhRdeqGp0l5c6Zl0IjUvn6vAeslrjG7bgOuN4jHqQBRDbZA==",
                            PhoneNumber = "602222222",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fea4280d118141ea8ad96772f5894c3b",
                            TwoFactorEnabled = false,
                            UserName = "patient2"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            BirthNumber = "920808/8032",
                            ConcurrencyStamp = "659a392c-e04a-4c0c-ac51-57be5e8559c3",
                            Email = "karel.novotny@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Karel",
                            LastName = "Novotný",
                            LockoutEnabled = true,
                            MaxExaminationPerDay = 0,
                            NormalizedEmail = "KAREL.NOVOTNY@EMAIL.CZ",
                            NormalizedUserName = "PATIENT3",
                            PasswordHash = "AQAAAAEAACcQAAAAEGDwHucn5uWF1684moFrwbqoaym+z0IHUiN+/EDQnXgz6HiEbGnaqFT136phybDc4g==",
                            PhoneNumber = "603333333",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0cf9f4dd524c4d93a415dec579b84b39",
                            TwoFactorEnabled = false,
                            UserName = "patient3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.DoctorPatient", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", "Doctor")
                        .WithMany("DoctorPatients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", "Patient")
                        .WithMany("PatientDoctors")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Examination", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", "Doctor")
                        .WithMany("DoctorExaminations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hrubos.HospitalSystem.Domain.Entities.ExaminationType", "ExaminationType")
                        .WithMany("Examinations")
                        .HasForeignKey("ExaminationTypeId");

                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", "Patient")
                        .WithMany("PatientExaminations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Doctor");

                    b.Navigation("ExaminationType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.ExaminationResult", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Domain.Entities.Examination", "Examination")
                        .WithOne("Result")
                        .HasForeignKey("Hrubos.HospitalSystem.Domain.Entities.ExaminationResult", "ExaminationId");

                    b.Navigation("Examination");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Vaccination", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", "Patient")
                        .WithMany("Vaccinations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hrubos.HospitalSystem.Domain.Entities.VaccineType", "VaccineType")
                        .WithMany("Vaccinations")
                        .HasForeignKey("VaccineTypeId");

                    b.Navigation("Patient");

                    b.Navigation("VaccineType");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Infrastructure.Identity.User", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Domain.Entities.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Hrubos.HospitalSystem.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Examination", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.ExaminationType", b =>
                {
                    b.Navigation("Examinations");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Domain.Entities.VaccineType", b =>
                {
                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("Hrubos.HospitalSystem.Infrastructure.Identity.User", b =>
                {
                    b.Navigation("DoctorExaminations");

                    b.Navigation("DoctorPatients");

                    b.Navigation("PatientDoctors");

                    b.Navigation("PatientExaminations");

                    b.Navigation("Vaccinations");
                });
#pragma warning restore 612, 618
        }
    }
}
